def count_sentences_starting_with_b(text):
    sentences = text.split('.')
    count = sum(1 for sentence in sentences if sentence.strip().startswith('B'))
    total_lines = len(sentences)  
    print(f"Total number of lines: {total_lines}")
    print(f"Number of Sentences that start with letter B: {count}")
sample_input = '''The apple doesn't fall. ...
All that glitters are not gold. ...
A picture is worth a thousand words. ...
Beggers can't be choosers. ...
A bird in the hand. ...
Better safe than sorry. ...
An apple a day keeps doctor away. ...
Blood is thicker than water. ...'''
count_sentences_starting_with_b(sample_input)
